GET http://localhost:3001/api/persons

### Add a new person --> twice for Name must be unique
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Max Muster",
    "number": "1234567890"
}


### Delete a person
DELETE http://localhost:3001/api/persons/787906
